// <auto-generated />
using System;
using Exchange.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Exchange.Database.Migrations
{
    [DbContext(typeof(ExchangeDbContext))]
    [Migration("20250221171106_update_table_transactions_add_column_amountInUsdt")]
    partial class update_table_transactions_add_column_amountInUsdt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Exchange.Database.Models.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "security");
                });

            modelBuilder.Entity("Exchange.Domain.Entities.CommissionInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AmountTo")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("FixedFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PercentFee")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Commissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1357dce9-0c7b-4bcd-befc-1dbb0f11c9cb"),
                            AmountFrom = 0m,
                            AmountTo = 400m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 21, 17, 11, 5, 857, DateTimeKind.Unspecified).AddTicks(2973), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USDT",
                            FixedFee = 20m,
                            PercentFee = 0m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 2, 21, 17, 11, 5, 857, DateTimeKind.Unspecified).AddTicks(3036), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("2f537bf1-d79c-487e-9247-b421ac051e00"),
                            AmountFrom = 400m,
                            AmountTo = 800m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 21, 17, 11, 5, 857, DateTimeKind.Unspecified).AddTicks(3043), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USDT",
                            PercentFee = 0.15m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 2, 21, 17, 11, 5, 857, DateTimeKind.Unspecified).AddTicks(3045), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("aeee4387-dca7-47a0-bffa-f6c6fc8f4bd8"),
                            AmountFrom = 800m,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 2, 21, 17, 11, 5, 857, DateTimeKind.Unspecified).AddTicks(3059), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "USDT",
                            PercentFee = 0.05m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 2, 21, 17, 11, 5, 857, DateTimeKind.Unspecified).AddTicks(3061), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Exchange.Domain.Entities.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountFrom")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("AmountTo")
                        .HasColumnType("decimal(18,9)");

                    b.Property<decimal>("AmountToInUsdt")
                        .HasColumnType("numeric");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,9)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CryptoNetworkCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CryptoNetworkName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrencyFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrencyTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FiatNetworkCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FiatNetworkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumberUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WalletAddressAdmin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WalletAddressUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Exchange.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Exchange.Domain.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Exchange.Domain.Entities.UserEntity", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Exchange.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
